"""Shared controller contracts and the public PyRatatui execution projection."""

from blackcell.interfaces.tui.app import (
    TuiApp,
    TuiControllerFactory,
    TuiFrame,
    TuiIdempotencyFactory,
    TuiInputMode,
    TuiKeyEvent,
    TuiRunAction,
    TuiShellController,
    TuiTerminal,
    TuiTerminalFactory,
    TuiView,
    TuiWorkflowOperation,
)
from blackcell.interfaces.tui.controller import (
    MAX_TUI_RETAINED_EVENTS,
    ServiceStatus,
    TuiClient,
    TuiController,
    TuiError,
    TuiFailureCode,
    TuiOperation,
    TuiProjection,
)
from blackcell.interfaces.tui.cursor import (
    TUI_CURSOR_SCHEMA,
    TuiCursorCheckpoint,
    TuiCursorError,
    TuiCursorFailureCode,
    TuiCursorStore,
    TuiCursorWitness,
    tui_endpoint_id,
)

__all__ = [
    "MAX_TUI_RETAINED_EVENTS",
    "TUI_CURSOR_SCHEMA",
    "ServiceStatus",
    "TuiApp",
    "TuiClient",
    "TuiController",
    "TuiControllerFactory",
    "TuiCursorCheckpoint",
    "TuiCursorError",
    "TuiCursorFailureCode",
    "TuiCursorStore",
    "TuiCursorWitness",
    "TuiError",
    "TuiFailureCode",
    "TuiFrame",
    "TuiIdempotencyFactory",
    "TuiInputMode",
    "TuiKeyEvent",
    "TuiOperation",
    "TuiProjection",
    "TuiRunAction",
    "TuiShellController",
    "TuiTerminal",
    "TuiTerminalFactory",
    "TuiView",
    "TuiWorkflowOperation",
    "tui_endpoint_id",
]
