provider = "github"

[repository]
owner = "kmosoti"
name = "blackcell"
node_id = "R_kgDOTH7xUQ"

[project]
id = "PVT_kwHOAtZ1m84BcCSO"
title = "BlackCell"
number = 7
url = "https://github.com/users/kmosoti/projects/7"
