"""Authenticated HTTP adapter and bounded runtime contracts."""

from importlib import import_module
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from blackcell.interfaces.http.app import PRESENTATION_MEDIA_TYPE, create_http_app
from blackcell.interfaces.http.contracts import (
    MAX_REQUEST_BODY_BYTES,
    MAX_RESPONSE_BODY_BYTES,
    MAX_RUN_QUERY_PAGE_SIZE,
    MAX_RUN_QUERY_SCAN_EVENTS,
    MAX_RUNTIME_EVENT_PAGE_SIZE,
    RUN_QUERY_MEDIA_TYPE,
    RUN_QUERY_RESULT_MEDIA_TYPE,
    AcceptanceCheck,
    CancelRunRequest,
    ErrorResponse,
    HealthResponse,
    IntentRequest,
    IntentResponse,
    NodeBudget,
    PlanEffect,
    PlanNode,
    PlanRequest,
    PlanResponse,
    ProjectRequest,
    ProjectResponse,
    ReplayArtifactIntegrity,
    ReplayArtifactResponse,
    ReplayArtifactRole,
    ReplayFindingCode,
    ReplayFindingResponse,
    ReplayResponse,
    RunBudgetUsageResponse,
    RunNodeQueryResponse,
    RunNodeStatus,
    RunQueryItem,
    RunQueryRequest,
    RunQueryResponse,
    RunRequest,
    RunResponse,
    RunStatus,
    RunSurfaceWindow,
    RuntimeEventPageResponse,
    RuntimeEventResponse,
    RuntimeEventType,
    StrictStruct,
    VerificationReplayFindingCode,
    VerificationReplayLifecycle,
    VerificationReplayResponse,
    VerificationVerdict,
    WireContractError,
    contract_to_builtins,
    contract_to_json_builtins,
    convert_contract,
    decode_contract,
    decode_response_contract,
    encode_contract,
    plan_topological_order,
)
from blackcell.interfaces.http.ports import (
    RuntimeApiError,
    RuntimeApiFailureCode,
    RuntimeApiPort,
    RuntimeArtifactPayload,
)
from blackcell.interfaces.http.quota import RequestQuotaPort, SlidingWindowRequestQuota
from blackcell.interfaces.http.web import (
    WEB_SOCKET_PATH,
    IssuedWebTicket,
    WebConnectionLimiter,
    WebSocketTicketResponse,
    WebTicketAuthority,
    WebTicketError,
    WebTicketFailureCode,
)


def __getattr__(name: str) -> Any:
    if name in {"PRESENTATION_MEDIA_TYPE", "create_http_app"}:
        return getattr(import_module("blackcell.interfaces.http.app"), name)
    raise AttributeError(name)


__all__ = [
    "MAX_REQUEST_BODY_BYTES",
    "MAX_RESPONSE_BODY_BYTES",
    "MAX_RUNTIME_EVENT_PAGE_SIZE",
    "MAX_RUN_QUERY_PAGE_SIZE",
    "MAX_RUN_QUERY_SCAN_EVENTS",
    "PRESENTATION_MEDIA_TYPE",
    "RUN_QUERY_MEDIA_TYPE",
    "RUN_QUERY_RESULT_MEDIA_TYPE",
    "WEB_SOCKET_PATH",
    "AcceptanceCheck",
    "CancelRunRequest",
    "ErrorResponse",
    "HealthResponse",
    "IntentRequest",
    "IntentResponse",
    "IssuedWebTicket",
    "NodeBudget",
    "PlanEffect",
    "PlanNode",
    "PlanRequest",
    "PlanResponse",
    "ProjectRequest",
    "ProjectResponse",
    "ReplayArtifactIntegrity",
    "ReplayArtifactResponse",
    "ReplayArtifactRole",
    "ReplayFindingCode",
    "ReplayFindingResponse",
    "ReplayResponse",
    "RequestQuotaPort",
    "RunBudgetUsageResponse",
    "RunNodeQueryResponse",
    "RunNodeStatus",
    "RunQueryItem",
    "RunQueryRequest",
    "RunQueryResponse",
    "RunRequest",
    "RunResponse",
    "RunStatus",
    "RunSurfaceWindow",
    "RuntimeApiError",
    "RuntimeApiFailureCode",
    "RuntimeApiPort",
    "RuntimeArtifactPayload",
    "RuntimeEventPageResponse",
    "RuntimeEventResponse",
    "RuntimeEventType",
    "SlidingWindowRequestQuota",
    "StrictStruct",
    "VerificationReplayFindingCode",
    "VerificationReplayLifecycle",
    "VerificationReplayResponse",
    "VerificationVerdict",
    "WebConnectionLimiter",
    "WebSocketTicketResponse",
    "WebTicketAuthority",
    "WebTicketError",
    "WebTicketFailureCode",
    "WireContractError",
    "contract_to_builtins",
    "contract_to_json_builtins",
    "convert_contract",
    "create_http_app",
    "decode_contract",
    "decode_response_contract",
    "encode_contract",
    "plan_topological_order",
]
